version: "3.7"

services:
  web:
    expose:
      - 3000
    env_file:
      - ./.env.prod
    build:
      context: ./services/web
      dockerfile: Dockerfile.prd
    volumes:
      - ./services/web/:/usr/src/app/
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443