# pull official base image
FROM python:3.9.5-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# Setting PYTHONUNBUFFERED to a non empty value ensures that the python output is sent straight to terminal 
# (e.g. your container log) without being first buffered and that you can see the output of your application (e.g. django logs) in real time.

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app/

CMD ["flask", "run", "-h", "0.0.0.0", "-p", "3000"]

